package com.reborn.modularmachinery.client;

import com.reborn.modularmachinery.ModularMachineryReborn;
import com.reborn.modularmachinery.block.ModBlocks;
import net.minecraft.network.chat.Component;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackSource;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraftforge.event.AddPackFindersEvent;

/**
 * Contributes {@link GeneratedControllerPack} so controllers declared by a pack author have a model.
 *
 * <p>The pack is only worth adding when there is something in it, so a normal install contributes nothing and
 * the pack list stays clean.
 */
public final class GeneratedResources {

    /** 1.20.1 resource pack format. */
    private static final int PACK_FORMAT = 15;

    public static void onAddPackFinders(AddPackFindersEvent event) {
        if (event.getPackType() != PackType.CLIENT_RESOURCES) {
            return;
        }
        // 0.27.0: the pack now carries a second namespace's worth of files — the `modularcontroller`
        // compatibility controllers — so "there is something for the mod's own namespace" is no longer the
        // question. Both halves are counted, and both are generated by GeneratedControllerPack.
        int generated = ModBlocks.controllersNeedingGeneratedAssets().size()
                + ModBlocks.MOC_CONTROLLERS.size();
        if (generated == 0) {
            return;
        }
        ModularMachineryReborn.LOGGER.info("[{}] Generating controller models for {} machine declaration(s) "
                + "in the config directory, in the mod's own namespace and in '{}'",
                ModularMachineryReborn.MOD_ID, generated,
                com.reborn.modularmachinery.block.MocNamespace.NAMESPACE);
        event.addRepositorySource(packs -> packs.accept(Pack.create(
                ModularMachineryReborn.MOD_ID + "_generated_controllers",
                Component.literal("Modular Machinery Reborn: generated controller models"),
                true,
                GeneratedControllerPack::new,
                new Pack.Info(Component.literal("Controller blockstates and item models for machines declared "
                        + "in config/modular_machinery_reborn/machinery/"), PACK_FORMAT, FeatureFlags.VANILLA_SET),
                PackType.CLIENT_RESOURCES,
                Pack.Position.TOP,
                true,
                PackSource.BUILT_IN)));
    }

    private GeneratedResources() {
    }
}
